# Generated by Django 4.1.6 on 2023-04-03 00:00

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("bakery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postimage",
            name="images",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WebP",
                keep_meta=True,
                quality=1,
                scale=None,
                size=[1920, 1080],
                upload_to="img/post/",
            ),
        ),
    ]
